import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import CardContainer from "../components/CardContainer";
import ImageContainer from "../components/ImageContainer";


export default function Home() {
  const imgRef = useRef<HTMLImageElement>(null);
  const [result, setResult] = useState(0);

  return (
    <>
      <Head>
        <title>Glaucoma Detector</title>
        <meta
          name="a simple glaucoma detecion app."
          content="Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold m-5">Glaucoma Detector</h1>
        <div className="md:flex md:h-full">
          <ImageContainer
            imageRef={imgRef}
            instructions="Drop Your Image Here Or"
            multiple={false}
          />
          <CardContainer imageRef={imgRef} />
        </div>
      </main>
    </>
  );
}
